name: build
on:
    push:
        branches:
        - users/*/*
    pull_request:
        branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@main

      - id: setup-java
        name: Set up JDK 22
        uses: actions/setup-java@main
        with:
          distribution: 'oracle'
          java-version: '22'
          
      - id: run
        name: Run app
        run: javac --enable-preview --source src/*.java 